### ISSUE TITLE
Use js2xml to parse the JSON object with data

### ISSUE THREAD

**Issue by rubik** [BrianDAllen/yahoo_finance_pandas#1]
Thanks for the library! It's very useful now that `pandas-datareader` stopped working. I want to suggest an improvement.

Using indices to extract the JSON object with the data is very fragile and we risk that it will break again as soon as the ordering of some keys changes or something like that.

Instead, you could use [js2xml](https://github.com/scrapinghub/js2xml) to convert the JS variable into an XML document that you can easily access with XPath or CSS selectors. That's more robust. For this solution a method to extract the right `<script>` tag with the data. For that BeautifulSoup or `scrapy.Selector` can be used.

**Comment by BrianDAllen** [comment]
Glad you find it useful and thanks for the suggestion. I won't have time to check out js2xml for some time, but If you want to submit a pull request with the changes, I'll review it.
